name: PREPROD - Build and Publish Artifact
 
on: [push]

permissions:
  id-token: write 
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Register Build Artifact
        uses: cloudbees-io-gha/register-build-artifact@v2
        with:
          name: "demo-test-service"
          version: "1.0.0"
          url: "docker.io/hdevanan/demo-service-1:1.0.0"
          digest: "${{ steps.image-digest.outputs.digest }}"
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"      
